services:
  # Servicio de MongoDB
  mongo:
    image: mongo:7
    container_name: todo-api-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  # Servicio de la API
  api:
    build: .
    container_name: todo-api
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - mongo
    networks:
      - todo-network
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge
